CREATE TABLE "categories" (
  "category_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text
);

CREATE TABLE "budgets" (
  "budget_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" int,
  "amount" int,
  "month" int,
  "year" int
);

CREATE TABLE "expenses" (
  "expense_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" int,
  "amount" int,
  "description" text,
  "date" varchar
);

ALTER TABLE "budgets" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("category_id");

ALTER TABLE "expenses" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("category_id");
